apiVersion: v1
kind: Pod
metadata: 
  name: hello-pod
  namespace: roboshop
spec:
  containers: 
- name: hello-pod
  image: nginx
  ports: 
  - containerPort: 80
  resources:
    requests:
      cpu: "100"
      memorey: "68Mi"
    limits:
      cpu: "200m"
      memorey: "128Mi"

